export const PUBLISHER_REQUEST = "PUBLISHER_REQUEST";
export const PUBLISHER_SUCCESS = "PUBLISHER_SUCCESS";
export const PUBLISHER_FAIL = "PUBLISHER_FAIL";

// export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
// export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
// export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS";
